server:
  port: 8090

spring:
  h2:
    console:
      enable: true
      path: /h2

  datasource:
    driverClass: org.h2.driver
    username: sa
    password:


springdoc:
  swagger-ui:
    path: /swagger